// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world.proto

#ifndef PROTOBUF_world_2eproto__INCLUDED
#define PROTOBUF_world_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace world {
class Location;
class LocationDefaultTypeInternal;
extern LocationDefaultTypeInternal _Location_default_instance_;
class Location_Area;
class Location_AreaDefaultTypeInternal;
extern Location_AreaDefaultTypeInternal _Location_Area_default_instance_;
class Location_Area_Terrain;
class Location_Area_TerrainDefaultTypeInternal;
extern Location_Area_TerrainDefaultTypeInternal _Location_Area_Terrain_default_instance_;
}  // namespace world

namespace world {

namespace protobuf_world_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_world_2eproto

// ===================================================================

class Location_Area_Terrain : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:world.Location.Area.Terrain) */ {
 public:
  Location_Area_Terrain();
  virtual ~Location_Area_Terrain();

  Location_Area_Terrain(const Location_Area_Terrain& from);

  inline Location_Area_Terrain& operator=(const Location_Area_Terrain& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Location_Area_Terrain& default_instance();

  static inline const Location_Area_Terrain* internal_default_instance() {
    return reinterpret_cast<const Location_Area_Terrain*>(
               &_Location_Area_Terrain_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Location_Area_Terrain* other);

  // implements Message ----------------------------------------------

  inline Location_Area_Terrain* New() const PROTOBUF_FINAL { return New(NULL); }

  Location_Area_Terrain* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Location_Area_Terrain& from);
  void MergeFrom(const Location_Area_Terrain& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Location_Area_Terrain* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 xLoc = 1;
  void clear_xloc();
  static const int kXLocFieldNumber = 1;
  ::google::protobuf::int32 xloc() const;
  void set_xloc(::google::protobuf::int32 value);

  // int32 yLoc = 2;
  void clear_yloc();
  static const int kYLocFieldNumber = 2;
  ::google::protobuf::int32 yloc() const;
  void set_yloc(::google::protobuf::int32 value);

  // int32 ttype = 3;
  void clear_ttype();
  static const int kTtypeFieldNumber = 3;
  ::google::protobuf::int32 ttype() const;
  void set_ttype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:world.Location.Area.Terrain)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 xloc_;
  ::google::protobuf::int32 yloc_;
  ::google::protobuf::int32 ttype_;
  mutable int _cached_size_;
  friend struct protobuf_world_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Location_Area : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:world.Location.Area) */ {
 public:
  Location_Area();
  virtual ~Location_Area();

  Location_Area(const Location_Area& from);

  inline Location_Area& operator=(const Location_Area& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Location_Area& default_instance();

  static inline const Location_Area* internal_default_instance() {
    return reinterpret_cast<const Location_Area*>(
               &_Location_Area_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Location_Area* other);

  // implements Message ----------------------------------------------

  inline Location_Area* New() const PROTOBUF_FINAL { return New(NULL); }

  Location_Area* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Location_Area& from);
  void MergeFrom(const Location_Area& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Location_Area* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Location_Area_Terrain Terrain;

  // accessors -------------------------------------------------------

  // repeated .world.Location.Area.Terrain terrain = 2;
  int terrain_size() const;
  void clear_terrain();
  static const int kTerrainFieldNumber = 2;
  const ::world::Location_Area_Terrain& terrain(int index) const;
  ::world::Location_Area_Terrain* mutable_terrain(int index);
  ::world::Location_Area_Terrain* add_terrain();
  ::google::protobuf::RepeatedPtrField< ::world::Location_Area_Terrain >*
      mutable_terrain();
  const ::google::protobuf::RepeatedPtrField< ::world::Location_Area_Terrain >&
      terrain() const;

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:world.Location.Area)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::world::Location_Area_Terrain > terrain_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable int _cached_size_;
  friend struct protobuf_world_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Location : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:world.Location) */ {
 public:
  Location();
  virtual ~Location();

  Location(const Location& from);

  inline Location& operator=(const Location& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Location& default_instance();

  static inline const Location* internal_default_instance() {
    return reinterpret_cast<const Location*>(
               &_Location_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Location* other);

  // implements Message ----------------------------------------------

  inline Location* New() const PROTOBUF_FINAL { return New(NULL); }

  Location* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Location& from);
  void MergeFrom(const Location& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Location* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Location_Area Area;

  // accessors -------------------------------------------------------

  // repeated .world.Location.Area areas = 4;
  int areas_size() const;
  void clear_areas();
  static const int kAreasFieldNumber = 4;
  const ::world::Location_Area& areas(int index) const;
  ::world::Location_Area* mutable_areas(int index);
  ::world::Location_Area* add_areas();
  ::google::protobuf::RepeatedPtrField< ::world::Location_Area >*
      mutable_areas();
  const ::google::protobuf::RepeatedPtrField< ::world::Location_Area >&
      areas() const;

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // int32 width = 2;
  void clear_width();
  static const int kWidthFieldNumber = 2;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // int32 height = 3;
  void clear_height();
  static const int kHeightFieldNumber = 3;
  ::google::protobuf::int32 height() const;
  void set_height(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:world.Location)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::world::Location_Area > areas_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  mutable int _cached_size_;
  friend struct protobuf_world_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Location_Area_Terrain

// int32 xLoc = 1;
inline void Location_Area_Terrain::clear_xloc() {
  xloc_ = 0;
}
inline ::google::protobuf::int32 Location_Area_Terrain::xloc() const {
  // @@protoc_insertion_point(field_get:world.Location.Area.Terrain.xLoc)
  return xloc_;
}
inline void Location_Area_Terrain::set_xloc(::google::protobuf::int32 value) {
  
  xloc_ = value;
  // @@protoc_insertion_point(field_set:world.Location.Area.Terrain.xLoc)
}

// int32 yLoc = 2;
inline void Location_Area_Terrain::clear_yloc() {
  yloc_ = 0;
}
inline ::google::protobuf::int32 Location_Area_Terrain::yloc() const {
  // @@protoc_insertion_point(field_get:world.Location.Area.Terrain.yLoc)
  return yloc_;
}
inline void Location_Area_Terrain::set_yloc(::google::protobuf::int32 value) {
  
  yloc_ = value;
  // @@protoc_insertion_point(field_set:world.Location.Area.Terrain.yLoc)
}

// int32 ttype = 3;
inline void Location_Area_Terrain::clear_ttype() {
  ttype_ = 0;
}
inline ::google::protobuf::int32 Location_Area_Terrain::ttype() const {
  // @@protoc_insertion_point(field_get:world.Location.Area.Terrain.ttype)
  return ttype_;
}
inline void Location_Area_Terrain::set_ttype(::google::protobuf::int32 value) {
  
  ttype_ = value;
  // @@protoc_insertion_point(field_set:world.Location.Area.Terrain.ttype)
}

// -------------------------------------------------------------------

// Location_Area

// string name = 1;
inline void Location_Area::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Location_Area::name() const {
  // @@protoc_insertion_point(field_get:world.Location.Area.name)
  return name_.GetNoArena();
}
inline void Location_Area::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:world.Location.Area.name)
}
#if LANG_CXX11
inline void Location_Area::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:world.Location.Area.name)
}
#endif
inline void Location_Area::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:world.Location.Area.name)
}
inline void Location_Area::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:world.Location.Area.name)
}
inline ::std::string* Location_Area::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:world.Location.Area.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Location_Area::release_name() {
  // @@protoc_insertion_point(field_release:world.Location.Area.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Location_Area::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:world.Location.Area.name)
}

// repeated .world.Location.Area.Terrain terrain = 2;
inline int Location_Area::terrain_size() const {
  return terrain_.size();
}
inline void Location_Area::clear_terrain() {
  terrain_.Clear();
}
inline const ::world::Location_Area_Terrain& Location_Area::terrain(int index) const {
  // @@protoc_insertion_point(field_get:world.Location.Area.terrain)
  return terrain_.Get(index);
}
inline ::world::Location_Area_Terrain* Location_Area::mutable_terrain(int index) {
  // @@protoc_insertion_point(field_mutable:world.Location.Area.terrain)
  return terrain_.Mutable(index);
}
inline ::world::Location_Area_Terrain* Location_Area::add_terrain() {
  // @@protoc_insertion_point(field_add:world.Location.Area.terrain)
  return terrain_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::world::Location_Area_Terrain >*
Location_Area::mutable_terrain() {
  // @@protoc_insertion_point(field_mutable_list:world.Location.Area.terrain)
  return &terrain_;
}
inline const ::google::protobuf::RepeatedPtrField< ::world::Location_Area_Terrain >&
Location_Area::terrain() const {
  // @@protoc_insertion_point(field_list:world.Location.Area.terrain)
  return terrain_;
}

// -------------------------------------------------------------------

// Location

// string name = 1;
inline void Location::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Location::name() const {
  // @@protoc_insertion_point(field_get:world.Location.name)
  return name_.GetNoArena();
}
inline void Location::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:world.Location.name)
}
#if LANG_CXX11
inline void Location::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:world.Location.name)
}
#endif
inline void Location::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:world.Location.name)
}
inline void Location::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:world.Location.name)
}
inline ::std::string* Location::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:world.Location.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Location::release_name() {
  // @@protoc_insertion_point(field_release:world.Location.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Location::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:world.Location.name)
}

// int32 width = 2;
inline void Location::clear_width() {
  width_ = 0;
}
inline ::google::protobuf::int32 Location::width() const {
  // @@protoc_insertion_point(field_get:world.Location.width)
  return width_;
}
inline void Location::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:world.Location.width)
}

// int32 height = 3;
inline void Location::clear_height() {
  height_ = 0;
}
inline ::google::protobuf::int32 Location::height() const {
  // @@protoc_insertion_point(field_get:world.Location.height)
  return height_;
}
inline void Location::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:world.Location.height)
}

// repeated .world.Location.Area areas = 4;
inline int Location::areas_size() const {
  return areas_.size();
}
inline void Location::clear_areas() {
  areas_.Clear();
}
inline const ::world::Location_Area& Location::areas(int index) const {
  // @@protoc_insertion_point(field_get:world.Location.areas)
  return areas_.Get(index);
}
inline ::world::Location_Area* Location::mutable_areas(int index) {
  // @@protoc_insertion_point(field_mutable:world.Location.areas)
  return areas_.Mutable(index);
}
inline ::world::Location_Area* Location::add_areas() {
  // @@protoc_insertion_point(field_add:world.Location.areas)
  return areas_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::world::Location_Area >*
Location::mutable_areas() {
  // @@protoc_insertion_point(field_mutable_list:world.Location.areas)
  return &areas_;
}
inline const ::google::protobuf::RepeatedPtrField< ::world::Location_Area >&
Location::areas() const {
  // @@protoc_insertion_point(field_list:world.Location.areas)
  return areas_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace world

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_world_2eproto__INCLUDED
